package com.spintum.preexam;


public class MyData {

     static String[] nameArray = {"MATHS", "PHYSICS", "CHEMISTRY", "BIOLOGY", "COMPUTER SCIENCE"};
    static String[] versionArray = {
            "\n"+"Unit1:Relations and Functions-Relations and Functions online test for class 12 Mathematics. These online MCQ tests includes all main concepts of the chapter in CBSE class 12 Mathematics. It is also useful for CBSE JEE (mains) and CBSE NEET (UG)"+"\n"+
                    "\n"+"Unit2:Functions-Relations and Functions online test for class 12 Mathematics. These online MCQ tests includes all main concepts of the chapter in CBSE class 12 Mathematics. It is also useful for CBSE JEE (mains) and CBSE NEET (UG)."+"\n"+
                    "\n"+"Unit3:online test for class 12 Mathematics. These online MCQ tests includes all main concepts of the chapter in CBSE class 12 Mathematics. It is also useful for CBSE JEE (mains) and CBSE NEET (UG)"+"\n"+
                    "\n"+ "Unit4:And Functions-Relations and Functions online test for class 12 Mathematics. These online MCQ tests includes all main concepts of the chapter in CBSE class 12 Mathematics. It is also useful for CBSE JEE (mains) and CBSE NEET (UG)"+"\n"+
                    "\n"+ "Unit5:Relations and Functions-Relations and Functions online test for class 12 Mathematics. These online MCQ tests includes all main concepts of the chapter in CBSE class 12 Mathematics. It is also useful for CBSE JEE (mains) and CBSE NEET (UG).",
            "\n"+"Unit1:Relations and Functions online test for class 12 Mathematics. These online MCQ tests includes all main concepts of the chapter in CBSE class 12 Mathematics. It is also useful for CBSE JEE (mains) and CBSE NEET (UG)"+"\n"+
                    "\n"+"Unit2:Relations and Functions online test for class 12 Mathematics. These online MCQ tests includes all main concepts of the chapter in CBSE class 12 Mathematics. It is also useful for CBSE JEE (mains) and CBSE NEET (UG)."+"\n"+
                    "\n"+"Unit3:Relations and Functions online test for class 12 Mathematics. These online MCQ tests includes all main concepts of the chapter in CBSE class 12 Mathematics. It is also useful for CBSE JEE (mains) and CBSE NEET (UG)"+"\n"+
                    "\n"+"Unit4:Relations and Functions online test for class 12 Mathematics. These online MCQ tests includes all main concepts of the chapter in CBSE class 12 Mathematics. It is also useful for CBSE JEE (mains) and CBSE NEET (UG)"+"\n"+
                    "\n"+"Unit5:Relations and Functions online test for class 12 Mathematics. These online MCQ tests includes all main concepts of the chapter in CBSE class 12 Mathematics. It is also useful for CBSE JEE (mains) and CBSE NEET (UG).",
            "\n"+"Unit1:Optics and Optical Instruments Ray Optics: Reflection of light, spherical mirrors, mirror formula, refraction of light, total internal reflection and its applications, optical fibres, refraction at spherical surfaces, lenses, thin lens formula, lensmaker's formula, magnification, power of a lens, combination of thin lenses in contact, combination of a lens and a mirror, refraction and dispersion of light through"+"\n"+
                    "\n"+"Unit2:Reflection of light, spherical mirrors, mirror formula, refraction of light, total internal reflection and its applications, optical fibres, refraction at spherical surfaces, lenses, thin lens formula, lensmaker's formula, magnification, power of a lens, combination of thin lenses in contact, combination of a lens and a mirror, refraction and dispersion of light through"+"\n"+
                    "\n"+"Unit3:Spherical mirrors, mirror formula, refraction of light, total internal reflection and its applications, optical fibres, refraction at spherical surfaces, lenses, thin lens formula, lensmaker's formula, magnification, power of a lens, combination of thin lenses in contact, combination of a lens and a mirror, refraction and dispersion of light through"+"\n"+
                    "\n"+"Unit4:Instruments Ray Optics: Reflection of light, spherical mirrors, mirror formula, refraction of light, total internal reflection and its applications, optical fibres, refraction at spherical surfaces, lenses, thin lens formula, lensmaker's formula, magnification, power of a lens, combination of thin lenses in contact, combination of a lens and a mirror, refraction and dispersion of light through"+"\n"+
                    "\n"+"Unit5:Optical Instruments Ray Optics: Reflection of light, spherical mirrors, mirror formula, refraction of light, total internal reflection and its applications, optical fibres, refraction at spherical surfaces, lenses, thin lens formula, lensmaker's formula, magnification, power of a lens, combination of thin lenses in contact, combination of a lens and a mirror, refraction and dispersion of light through",
            "\n"+"Unit1:Reflection and refraction of plane wave at a plane surface using wave fronts. Proof of laws of reflection and refraction using Huygen's principle. Interference, Young's double slit experiment and expression for fringe width, coherent sources and sustained interference of light, diffraction due to a single slit, width of central maximum, resolving power of microscope and astronomical telescope, polarisation,"+"\n"+
                    "\n"+"Unit2:Wave front and Huygen's principle, reflection and refraction of plane wave at a plane surface using wave fronts. Proof of laws of reflection and refraction using Huygen's principle. Interference, Young's double slit experiment and expression for fringe width, coherent sources and sustained interference of light, diffraction due to a single slit, width of central maximum, resolving power of microscope and astronomical telescope, polarisation,"+"\n"+
                    "\n"+"Unit3:Wave front and Huygen's principle, reflection and refraction of plane wave at a plane surface using wave fronts. Proof of laws of reflection and refraction using Huygen's principle. Interference, Young's double slit experiment and expression for fringe width, coherent sources and sustained interference of light, diffraction due to a single slit, width of central maximum, resolving power of microscope and astronomical telescope, polarisation"+"\n"+
                    "\n"+"Unit4:Wave front and Huygen's principle, reflection and refraction of plane wave at a plane surface using wave fronts. Proof of laws of reflection and refraction using Huygen's principle. Interference, Young's double slit experiment and expression for fringe width, coherent sources and sustained interference of light, diffraction due to a single slit, width of central maximum, resolving power of microscope and astronomical telescope, polarisation"+"\n"+
                    "\n"+"Unit5:Wave front and Huygen's principle, reflection and refraction of plane wave at a plane surface using wave fronts. Proof of laws of reflection and refraction using Huygen's principle. Interference, Young's double slit experiment and expression for fringe width, coherent sources and sustained interference of light, diffraction due to a single slit, width of central maximum, resolving power of microscope and astronomical telescope, polarisation",
            "\n"+"Unit1:Wave front and Huygen's principle, reflection and refraction of plane wave at a plane surface using wave fronts. Proof of laws of reflection and refraction using Huygen's principle. Interference, Young's double slit experiment and expression for fringe width, coherent sources and sustained interference of light, diffraction due to a single slit, width of central maximum, resolving power of microscope and astronomical telescope, polarisation,"+"\n"+
                    "\n"+"Unit2:Wave front and Huygen's principle, reflection and refraction of plane wave at a plane surface using wave fronts. Proof of laws of reflection and refraction using Huygen's principle. Interference, Young's double slit experiment and expression for fringe width, coherent sources and sustained interference of light, diffraction due to a single slit, width of central maximum, resolving power of microscope and astronomical telescope, polarisation,"+"\n"+
                    "\n"+"Unit3:Wave front and Huygen's principle, reflection and refraction of plane wave at a plane surface using wave fronts. Proof of laws of reflection and refraction using Huygen's principle. Interference, Young's double slit experiment and expression for fringe width, coherent sources and sustained interference of light, diffraction due to a single slit, width of central maximum, resolving power of microscope and astronomical telescope, polarisation,"+"\n"+
                    "\n"+"Unit4:Wave front and Huygen's principle, reflection and refraction of plane wave at a plane surface using wave fronts. Proof of laws of reflection and refraction using Huygen's principle. Interference, Young's double slit experiment and expression for fringe width, coherent sources and sustained interference of light, diffraction due to a single slit, width of central maximum, resolving power of microscope and astronomical telescope, polarisation,"+"\n"+
                    "\n"+"Unit5:Huygen's principle, reflection and refraction of plane wave at a plane surface using wave fronts. Proof of laws of reflection and refraction using Huygen's principle. Interference, Young's double slit experiment and expression for fringe width, coherent sources and sustained interference of light, diffraction due to a single slit, width of central maximum, resolving power of microscope and astronomical telescope, polarisation"};

    static Integer[] drawableArray = {R.drawable.s1, R.drawable.s2, R.drawable.s3, R.drawable.s4, R.drawable.s5};
    static Integer[] id_ = {0, 1, 2, 3, 4};

}
